<?php
global $categories;
global $products;

$categories = [
    [
        'label' => 'DESKTOP',
        'clickUrl' => 'search.php?s=desktop'
    ],
    [
        'label' => 'LAPTOP',
        'clickUrl' => 'search.php?s=laptop'
    ],
    [
        'label' => 'KEYBOARD',
        'clickUrl' => 'search.php?s=keyboard'
    ],
    [
        'label' => 'MOUSE',
        'clickUrl' => 'search.php?s=mouse',
    ],
    [
        'label' => 'PRINTER',
        'clickUrl' => 'search.php?s=printer'
    ],
    [
        'label' => 'CABLE',
        'clickUrl' => 'search.php?s=cable'
    ],
    [
        'label' => 'THUMB DEVICE',
        'clickUrl' => 'search.php?s=thumb+device'
    ],
    [
        'label' => 'HARD DISK',
        'clickUrl' => 'search.php?s=hard+disk'
    ],
    [
        'label' => 'CCTV CAMERA AND ACCESSORIES',
        'clickUrl' => 'search.php?s=cctv+camera+accessories'
    ],
    [
        'label' => 'GST BILLING SOFTWARE',
        'clickUrl' => 'search.php?s=gst+billing+software'
    ]
];

$products = [
   
    [
        'id'=> '1',
        'title' => 'HP 15-DI0002-TU LAPTOP',
        'description' => ['',''],
        'originalPrice' => 'Rs. 28900',
        'sellPrice' => 'Rs. 28900 /-',
        'category' => 'hw',
        'tags' => 'mn',
        'clickUrl' => '#',
        'img' => 'HP15DI0002TU.jpg',
    ],
    [
        'id'=> '2',
        'title' => 'HP WIRED C-2500 COMBO Keyboard',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 850 /-',
        'category' => 'hw',
        'tags' => 'mn',
        'clickUrl' => '#',
        'img' => 'hpc2500.png',
    ],
    [
        'id'=> '3',
        'title' => 'I BALL WIRED COMBO Keyboard SHINY M.3',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 650 /-',
        'category' => 'hw',
        'tags' => 'mn',
        'clickUrl' => '#',
        'img' => 'I-M.3.jpeg',
    ],
    [
         'id'=> '4',
        'title' => 'DELL USB KEYBOARD KB - 216',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 450 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'DELL216.jpg',
    ],
    [
         'id'=> '5',
        'title' => 'CANON INK-JET G-3010 W Printer',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 11500/-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'CANON INK-JET.jpeg',
    ],
    [
         'id'=> '6',
        'title' => 'HP WIRELESS COMBO Keyboard 4SC12PA',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 1250 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'HP4SC12PA.jpg',
    ],
    [
         'id'=> '7',
        'title' => 'I BALL USB MOUSE STAYLES 36',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 260 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'style35.png',
    ],
    [
         
         'id'=> '8',
        'title' => 'EPSON L-3150 INK JET WIRELESS',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 12000 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'EPSONL-3150.jpg',
    
    ],
    [
         'id'=> '9',
        'title' => 'DELL USB MOUSE MS116',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 270 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'dellms116.jpg',
    ],
    [
         'id'=> '10',
        'title' => 'DELL WIRELESS KEYBOARD COMBO KM 117',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 1150 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'dellkm117.png',
    ],
    
    [
         'id'=> '12',
        'title' => 'ZEBION USB MOUSE HUNK',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 130 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'Zebionhunk.jpg',
    ],
      [
         'id'=> '13',
        'title' => 'ZEBION USB MOUSE SWAG',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 130 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'ZEBIONswag.jpg',
  
    ],
     [
         'id'=> '14',
        'title' => 'Zebion Ergo USB Keyboard',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 250 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'Zebion.jpg',
    ],
     [
         'id'=> '15',
        'title' => 'ZEBION USB MOUSE ROCKY',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 130 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'ZEBIONROCKY.jpg',
    ],
     [
         'id'=> '16',
        'title' => 'BROTHER DCP-L2520D PRINTER',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 12500 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'BROTHERL2520D.jpg',
    ],
     [
         'id'=> '17',
        'title' => 'BROTHER HL-L2321D PRINTER',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 7700 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'BROTHERL2321D.jpg',
    ],
     [
         'id'=> '18',
        'title' => 'BROTHER T-310 INK JET PRINTER',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 9800 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'BROTHERT-310.png',
    ],
     [
         'id'=> '19',
        'title' => 'BROTHER T-510 INK JET PRINTER WIRELESS',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 11800 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'BROTHERT-510.jpg',
    ],
    [
         'id'=> '20',
        'title' => 'CANON INK JET G-2010',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 9500 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'CANONG-2010.jpg',
    ],
    [
         'id'=> '21',
        'title' => 'CANON LBP-2900B',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 10350 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'canon2900.jpg',
    ],
    [
         'id'=> '22',
        'title' => 'CANON MF-3010',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 12350 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'CANONMF-3010.jpg',
    ],
    [
         'id'=> '23',
        'title' => 'EPSON L-3116 INK JET',
        'description' => ['',''],
        'originalPrice' => 'Rs. 70000',
        'sellPrice' => 'Rs. 10500 /-',
        'category' => '',
        'tags' => '',
        'clickUrl' => '#',
        'img' => 'EPSONL-3116.jpg',
    ],
];